### PR TITLE
Richer ci-result

### PR DESCRIPTION
**Pull request by mastoj**
### Description

The changes will add a richer json summary when running a CI build. Instead of "ci-result.json" that only has the score per page, this change will create a json that looks like this:

```
{
    summary: {
        score: 0.91,
        categories: {
              seo: 0.89,
              performance: 0.99
       }
    },
    route: [
        {
            path: "/"            
            score: 0.91,
            categories: {
                  seo: 0.89,
                  performance: 0.99
           }
        }
    ]
}
```

This will make it easier to create custom reports or store the result for reference. 

Notes:
* The categories will list all available categories.
* The summary score for the categories will assume that all routes have a score for each category, if that isn't the case the summary score might show an incorrect average.

### Linked Issues

Fixes: https://github.com/harlan-zw/unlighthouse/issues/98

### CODE REVIEW

**Comment by harlan-zw** [comment]
Hey @mastoj, thanks for the PR! 

The only issue with supporting this currently is that you are introducing a breaking change for anyone using the current output JSON.

So either we need to do this without the breaking change or it can be introduced behind a CLI flag which can become default in v1.

**Comment by rawalplawit** [comment]
While we're on this, I think we should also have an option to show these metrics in the JSON output as these are the metrics we often refer to for CWV.

image
image

**Comment by mastoj** [comment]
If you think this is a good idea in general I can add the flag (v1-report?) and also look at the other metrics. I guess they are available on each route?

**Comment by rawalplawit** [comment]
I haven't looked into the code much but we can get the data from the `result.result?.audits`. 

https://github.com/harlan-zw/unlighthouse/blob/dc9cee6038395d0e7ab6db31ba5233e7635cdb02/packages/cli/src/ci.ts#LL93C15-L93C42

Core Web Vitals seem to be sent from columnFields seems like we can send in our own if we want.
https://github.com/harlan-zw/unlighthouse/blob/main/packages/core/src/puppeteer/tasks/lighthouse.ts#L48

**Comment by mastoj** [comment]
I will give it a go and see where I end up. I hope to get to it today or during the weekend.

**Comment by mastoj** [comment]
I did eventually figure out how to deal with the options and config, so this is what I had time to do. Unfortunately I couldn't find the CWV metrics in the report, not sure why. The good part though is that adding them should not be a breaking change.

I've also updated the way I calculate the average so it is based on present values and not the number of routes. This means if some category is missing a result for some pages those pages will be ignored in the calculation.

**Comment by mastoj** [comment]
Not sure it follows the style and organization you like. I did try to improve some structure by breaking out the reporting pieces to separate functions, but it can probably be improved further. I was somewhat limited though since it seems like my dev environment isn't correctly set up for the project, so I have some errors in the IDE even when it builds perfectly fine.

**Comment by mastoj** [comment]
Found that the CWV should be set, https://github.com/harlan-zw/unlighthouse/blob/34a61a7de1d4a635547ae8d0b611b80b2b0b28b8/packages/core/src/puppeteer/tasks/lighthouse.ts#L46, weird that I couldn’t see it when running. Will look more tomorrow or in the weekend.

**Comment by harlan-zw** [comment]
> Not sure it follows the style and organization you like. I did try to improve some structure by breaking out the reporting pieces to separate functions, but it can probably be improved further. I was somewhat limited though since it seems like my dev environment isn't correctly set up for the project, so I have some errors in the IDE even when it builds perfectly fine.

Not sure if you use Discord but feel free to DM me if you need some help getting it set up.

The reporting features were mostly an after thought, for the v1 they will need to be refactored so happy for bigger changes.

**Comment by mastoj** [comment]
I think the format of the report is ok, since it is now easier to add more. The main things are "metrics" and "categories", and there are no limitation to how many they can contain. With that said, I am only picking metrics from a predefined set since the "audit" type contains many properties that does not align with the first set of metrics.

I have also added some unit test for the ci report generation and extracted a sample lighthouse report to use in the tests so we don't have to run against a web app to test it.

**Comment by harlan-zw** [comment]
Continued in https://github.com/harlan-zw/unlighthouse/pull/111

**Pull request closed without merging**
